export enum NAVIGATION_ACTION_TYPE {
  SET_ACTIVE_PATH = 'NAVIGATION_ACTION_TYPE.SET_ACTIVE_PATH',
  SET_PAGE_LOADING = 'NAVIGATION_ACTION_TYPE.SET_PAGE_LOADING',
  SET_QUERY = 'NAVIGATION_ACTION_TYPE.SET_QUERY',
}

export const NAVIGATION_STORE_NAME = 'NAVIGATION';
