import { SIGNUP_FORM_FIELD_KEY } from './frame/signup-form/signup.form.type';

export const SIGNUP_FIELD_NAME = {
  LOGIN: 'LOGIN',
  PASSWORD: 'PASSWORD',
};

export const SIGNUP_FORM_FIELD_NAME = {
  [SIGNUP_FORM_FIELD_KEY.LOGIN]: SIGNUP_FIELD_NAME.LOGIN,
  [SIGNUP_FORM_FIELD_KEY.PASSWORD]: SIGNUP_FIELD_NAME.PASSWORD,
};
